name: GoFiber-Jumpstart

services:
  postgres: 
    image: postgres:16-alpine
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: app_db
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - db_postgres:/var/lib/postgresql/data

  app:
    image: cosmtrek/air
    working_dir: /app
    volumes:
      - ./:/app/
    container_name: dev-app
    env_file:
      - .env
    ports:
      - "${APP_PORT}:3000"
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${APP_PORT}/livez"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  db_postgres: